fix:bugs in resubale build-test

diff --git a/.github/workflows/reusable-build-test.yml b/.github/workflows/reusable-build-test.yml
--- a/.github/workflows/reusable-build-test.yml
+++ b/.github/workflows/reusable-build-test.yml
@@ -3,35 +3,41 @@ name: Build & Test
 on:
   workflow_call:
     inputs:
-      matrix:
-        python-version: ["3.10", "3.11", "3.12"]
-
-    run_tests:
-      default: true
+      run_tests:
+        type: boolean
+        default: true
 
     outputs:
       test_result:
-        value: $ {{ steps.check_result.output.result }}
+        value: $ {{ jobs.build-test.outputs.test_result }}
 
 jobs:
-  steps:
-    - name: Check out Code
-      uses: actions/checkout@v4
+  build-test:
+    outputs:
+      test_result: ${{ steps.check_result.outputs.result }}
+    strategy:
+      matrix:
+        python-version: ["3.10", "3.11", "3.12"]
+    runs-on: ubuntu-latest
 
-    - name: Setup language run time
-      uses: actions/setup-python@v5
-      with:
-        python-version: ${{ matrix.python-version }}
+    steps:
+      - name: Check out Code
+        uses: actions/checkout@v4
 
-    - name: Install dependencies
-      run: pip install -r requirements.txt
+      - name: Setup language run time
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
 
-    - name: Run flake8 test only if run_test is true
-      id: check_result
-      if: $ {{ inputs.run_tests }} == true
-      run: |
-        flake8 app.py tests/
-        echo "result=$ {{ steps.check_result.outputs.test_result }}" >> $GITHUB_OUTPUT
+      - name: Install dependencies
+        run: pip install -r requirements.txt
 
-    - name: Set output with value passed or failed
-      run: echo "test result is $GITHUB_OUTPUT"
+      - name: Run flake8 test only if run_test is true
+        id: check_result
+        if: $ {{ inputs.run_tests == true }}
+        run: |
+          flake8 app.py tests/
+          if [ $? -eq 0]; then
+           echo "result=passed" >> $GITHUB_OUTPUT
+          else 
+           echo "result=failed" >> $GITHUB_OUTPUT
